spring.data.mongodb.uri=${MONGODBURL}

spring.jpa.properties.jakarta.persistence.sharedCache.mode=ENABLE_SELECTIVE

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=UTC

admin.user.password=${ADMINUSERPASSWORD}
admin.user.email=${ADMINUSEREMAIL}

firebase.secret=${FIREBASEJSON}